# Generated by Django 6.0 on 2025-12-16 16:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0010_documentsdg_alter_document_sdgs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('minutes', 'Minutes'), ('agenda', 'Agenda'), ('report', 'Report'), ('statement', 'Statement'), ('other', 'Other')], default='other', max_length=30)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document–Event Link',
                'verbose_name_plural': 'Document–Event Links',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('event_format', models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], max_length=20, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('ai_check_status', models.BooleanField(default=True)),
                ('human_check_status', models.BooleanField(default=False)),
                ('human_check_date', models.DateTimeField(blank=True, null=True)),
                ('human_notes', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('title_normalized', models.TextField(blank=True, editable=False, null=True)),
                ('description_normalized', models.TextField(blank=True, editable=False, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('beneficiary_groups', models.ManyToManyField(blank=True, related_name='events', to='documents.beneficiarygroup')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='events', through='events.DocumentEvent', to='documents.document')),
                ('eu_policy_alignments', models.ManyToManyField(blank=True, related_name='events', to='documents.eupolicy')),
                ('human_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_at', 'title'],
                'permissions': [('publish_event', 'Can publish event')],
            },
        ),
        migrations.AddField(
            model_name='documentevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='events.event'),
        ),
        migrations.CreateModel(
            name='EventActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_top', models.BooleanField(default=False)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.actor')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'verbose_name': 'Event–Actor Link',
                'verbose_name_plural': 'Event–Actor Links',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='events', through='events.EventActor', to='documents.actor'),
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField()),
                ('link_type', models.CharField(choices=[('website', 'Website'), ('registration', 'Registration'), ('agenda', 'Agenda'), ('stream', 'Streaming'), ('other', 'Other')], default='other', max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Link',
                'verbose_name_plural': 'Event Links',
            },
        ),
        migrations.CreateModel(
            name='EventSDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relevance_score', models.FloatField(blank=True, default=1.0, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.sdg')),
            ],
            options={
                'verbose_name': 'Event–SDG Link',
                'verbose_name_plural': 'Event–SDG Links',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='sdgs',
            field=models.ManyToManyField(blank=True, related_name='events', through='events.EventSDG', to='documents.sdg'),
        ),
        migrations.CreateModel(
            name='EventTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_top', models.BooleanField(default=False)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.theme')),
            ],
            options={
                'verbose_name': 'Event–Theme Link',
                'verbose_name_plural': 'Event–Theme Links',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='events', through='events.EventTheme', to='documents.theme'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_memberships', to='auth.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Member',
                'verbose_name_plural': 'Organization Members',
            },
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['event', 'role'], name='doc_event_role_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentevent',
            unique_together={('document', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='eventactor',
            unique_together={('event', 'actor')},
        ),
        migrations.AlterUniqueTogether(
            name='eventlink',
            unique_together={('event', 'url')},
        ),
        migrations.AlterUniqueTogether(
            name='eventsdg',
            unique_together={('event', 'sdg')},
        ),
        migrations.AlterUniqueTogether(
            name='eventtheme',
            unique_together={('event', 'theme')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_at'], name='event_start_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published'], name='event_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='event_search_vector_gin'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'user'], name='org_member_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'user')},
        ),
    ]
