# Generated by Django 5.2.12 on 2026-03-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_seed_event_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="eventsource",
            name="logo_url",
            field=models.URLField(blank=True),
        ),
    ]
