# Generated by Django 5.2.12 on 2026-03-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_seed_eucelac_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_relevant",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="If False, event is filtered out from public listing (e.g. courses, MOOCs).",
            ),
        ),
    ]
