# Generated by Django 5.2.12 on 2026-03-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_seed_iadb_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
