# Generated by Django 5.2.1 on 2025-06-04 19:35

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Political Actors", "Political Actors"),
                            (
                                "Research and Innovation Actors",
                                "Research and Innovation Actors",
                            ),
                            ("Economic Actors", "Economic Actors"),
                            ("Civil Society Actors", "Civil Society Actors"),
                            ("Uncategorised", "Uncategorised"),
                        ],
                        max_length=120,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "label_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "indexes": [
                    models.Index(fields=["label"], name="documents_a_label_44f522_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="actor_search_vector_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["label_normalized"],
                        name="actor_label_norm_trgm_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BeneficiaryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("General", "General"),
                            ("Age Groups", "Age Groups"),
                            ("Economic Groups", "Economic Groups"),
                            ("Social Groups", "Social Groups"),
                            ("Uncategorised", "Uncategorised"),
                        ],
                        max_length=64,
                    ),
                ),
                ("label", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "label_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="beneficiary_search_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["label_normalized"],
                        name="beneficiary_label_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BeneficiaryGroupRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "name_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="raw_ben_search_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name_normalized"],
                        name="raw_ben_name_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=120, null=True)),
                ("country", models.CharField(blank=True, max_length=120, null=True)),
                ("executive_summary", models.TextField(blank=True, null=True)),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "title_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "executive_summary_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "beneficiary_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        to="documents.beneficiarygroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Commitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "text_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_top", models.BooleanField(default=False)),
                ("relevance_score", models.FloatField(blank=True, null=True)),
                ("justification", models.TextField(blank=True, null=True)),
                (
                    "justification_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.actor",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="actors",
            field=models.ManyToManyField(
                related_name="documents",
                through="documents.DocumentActor",
                to="documents.actor",
            ),
        ),
        migrations.CreateModel(
            name="DocumentBeneficiaryGroupRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "raw_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.beneficiarygroupraw",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Beneficiary Link",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="beneficiary_groups_raw",
            field=models.ManyToManyField(
                blank=True,
                related_name="documents",
                through="documents.DocumentBeneficiaryGroupRaw",
                to="documents.beneficiarygroupraw",
            ),
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metric_name", models.CharField(max_length=200)),
                ("kpi_text", models.TextField(blank=True, null=True)),
                ("kpi_type", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "target_value",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "target_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=60, null=True)),
                ("timeframe", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "measurement_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "responsible_entity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sector", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "metric_name_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "kpi_text_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["metric_name"],
            },
        ),
        migrations.CreateModel(
            name="PracticalApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                (
                    "description_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practical_applications",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SDG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, unique=True
                    ),
                ),
                ("label", models.CharField(max_length=120, unique=True)),
                (
                    "label_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "SDG",
                "verbose_name_plural": "SDGs",
                "ordering": ["number"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="sdg_search_vector_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["label_normalized"],
                        name="sdg_label_norm_trgm_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="sdgs",
            field=models.ManyToManyField(
                blank=True, related_name="documents", to="documents.sdg"
            ),
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Digital Transformation & Strategy",
                                "Digital Transformation & Strategy",
                            ),
                            ("Technology & Innovation", "Technology & Innovation"),
                            ("Data & Governance", "Data & Governance"),
                            (
                                "Inclusion & Social Development",
                                "Inclusion & Social Development",
                            ),
                            (
                                "Regional & International Cooperation",
                                "Regional & International Cooperation",
                            ),
                            ("Uncategorised", "Uncategorised"),
                        ],
                        max_length=120,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "label_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "indexes": [
                    models.Index(fields=["label"], name="documents_t_label_78913d_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="theme_search_vector_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["label_normalized"],
                        name="theme_label_norm_trgm_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_top", models.BooleanField(default=False)),
                ("relevance_score", models.FloatField(blank=True, null=True)),
                ("justification", models.TextField(blank=True, null=True)),
                (
                    "justification_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.theme",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="themes",
            field=models.ManyToManyField(
                related_name="documents",
                through="documents.DocumentTheme",
                to="documents.theme",
            ),
        ),
        migrations.CreateModel(
            name="CommitmentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "commitment_class",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "text_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="documents.commitment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="commit_detail_search_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["text_normalized"],
                        name="commit_detail_text_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
                "unique_together": {("commitment", "text")},
            },
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="commitment_search_vector_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="commitment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["text_normalized"],
                name="commitment_text_norm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commitment",
            unique_together={("document", "text")},
        ),
        migrations.AddIndex(
            model_name="documentactor",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="doc_actor_search_vector_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="documentactor",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["justification_normalized"],
                name="doc_actor_just_norm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentactor",
            unique_together={("document", "actor")},
        ),
        migrations.AlterUniqueTogether(
            name="documentbeneficiarygroupraw",
            unique_together={("document", "raw_group")},
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="kpi_search_vector_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metric_name_normalized"],
                name="kpi_metric_name_norm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["kpi_text_normalized"],
                name="kpi_text_norm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kpi",
            unique_together={("document", "metric_name")},
        ),
        migrations.AddIndex(
            model_name="practicalapplication",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="practical_search_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="practicalapplication",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description_normalized"],
                name="practical_desc_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="practicalapplication",
            unique_together={("document", "description")},
        ),
        migrations.AddIndex(
            model_name="documenttheme",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="doc_theme_search_vector_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttheme",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["justification_normalized"],
                name="doc_theme_just_norm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documenttheme",
            unique_together={("document", "theme")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["event_date"], name="doc_date_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="doc_search_vector_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title_normalized"],
                name="doc_title_norm_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["executive_summary_normalized"],
                name="doc_exec_summary_norm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("title", "event_date")},
        ),
    ]
