# Generated by Django 5.2.3 on 2025-06-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="coverage_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Regional", "Regional"),
                    ("Bilateral", "Bilateral"),
                    ("Multilateral", "Multilateral"),
                    ("National", "Country Specific"),
                    ("Global", "Global"),
                    ("Sub-regional", "Sub-regional"),
                    ("Uncategorised", "Uncategorised"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
