# Generated by Django 5.2.1 on 2025-06-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("iso3", models.CharField(max_length=3, unique=True)),
                (
                    "iso2",
                    models.CharField(blank=True, max_length=2, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="document",
            name="city",
        ),
        migrations.RemoveField(
            model_name="document",
            name="country",
        ),
        migrations.AddField(
            model_name="document",
            name="event_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.city",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="documents.country",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="countries_involved",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_in_documents",
                to="documents.country",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="event_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.country",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="lead_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_documents",
                to="documents.country",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "country")},
        ),
    ]
