# Generated by Django 5.2.1 on 2025-06-01 05:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_agreementtype_beneficiarygroup_country_sdggoal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="title_normalized",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name="document",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="doc_search_vector_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title_normalized"],
                name="doc_title_norm_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
