# Generated by Django 5.2.3 on 2025-06-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_coverage_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="coverage_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Regional", "Regional"),
                    ("Bilateral", "Bilateral"),
                    ("Multilateral", "Multilateral"),
                    ("Global", "Global"),
                    ("Sub-regional", "Sub-regional"),
                    ("Uncategorised", "Uncategorised"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
