# Generated by Django 5.2.1 on 2025-06-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dialogues_eu-lac", "Dialogues EU-LAC"),
                    ("dialogues_bilateral", "Dialogues Bilateral"),
                    ("dialogues_eu-country", "Dialogues EU-Country"),
                    ("dialogues_multilateral", "Dialogues multilateral"),
                    ("agreements_eu-lac", "Agreements EU-LAC"),
                    ("agreements_bilateral", "Agreements Bilateral"),
                    ("agreements_multilateral", "Agreements Multilateral"),
                    ("agreements_country_specific", "Agreements Country Specific"),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="legal_bindingness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("politically-binding", "Politically-binding"),
                    ("legally-binding", "Legally-binding"),
                    ("non-binding", "Non-Binding"),
                    ("uncategorised", "Uncategorised"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
