# Generated by Django 5.2.1 on 2025-06-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_actor_category_alter_actor_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agreement_eu-lac", "Agreement EU-LAC"),
                    ("agreement_eu-lac", "Agreement EU-LAC"),
                    ("dialogues_eu-lac", "Dialogues EU-LAC"),
                    ("dialogues_bilateral", "Dialogues Bilateral"),
                    ("dialogues_multilateral", "Dialogues Multilateral"),
                    ("agreements_eu-lac", "Agreements EU-LAC"),
                    ("agreements_bilateral", "Agreements Bilateral"),
                    ("agreements_multilateral", "Agreements Multilateral"),
                    ("agreements_country_specific", "Agreements Country Specific"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
