# Generated by Django 5.2.1 on 2025-06-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_sourcefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="event_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("presencial", "Presencial"),
                    ("virtual", "Virtual"),
                    ("hybrid", "Hybrid"),
                ],
                help_text="Format of the event (in-person, virtual, or hybrid)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="external_link",
            field=models.URLField(
                blank=True,
                help_text="External link to the source file (if applicable)",
                null=True,
            ),
        ),
    ]
