# Generated by Django 5.2.3 on 2025-06-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_coverage_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiarygroup",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SMEs / Businesses", "SMEs / Businesses"),
                    ("Start-ups / Innovators", "Start-ups / Innovators"),
                    ("Large Corporations", "Large Corporations"),
                    ("Researchers & Academia", "Researchers & Academia"),
                    ("Students & Youth", "Students & Youth"),
                    ("Migrants & Refugees", "Migrants & Refugees"),
                    ("Women & Girls", "Women & Girls"),
                    ("Rural & Remote Communities", "Rural & Remote Communities"),
                    (
                        "Indigenous Peoples & Ethnic Groups",
                        "Indigenous Peoples & Ethnic Groups",
                    ),
                    ("Persons with Disabilities", "Persons with Disabilities"),
                    ("General Citizens / Consumers", "General Citizens / Consumers"),
                    ("Public Sector / Governments", "Public Sector / Governments"),
                    ("Civil Society / NGOs", "Civil Society / NGOs"),
                    ("Farmers & Primary Producers", "Farmers & Primary Producers"),
                    ("Health Sector", "Health Sector"),
                    ("Investors & Financial Actors", "Investors & Financial Actors"),
                    ("Uncategorised", "Uncategorised"),
                ],
                max_length=64,
            ),
        ),
    ]
