# Generated by Django 5.2.1 on 2025-06-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_document_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Political Actors", "Political Actors"),
                    (
                        "Research and Innovation Actors",
                        "Research and Innovation Actors",
                    ),
                    ("Economic Actors", "Economic Actors"),
                    ("Civil Society Actors", "Civil Society Actors"),
                    ("Uncategorised", "Uncategorised"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="label",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="commitmentdetail",
            name="commitment_class",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="coverage_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Regional", "Regional"),
                    ("Bilateral", "Bilateral"),
                    ("Multilateral", "Multilateral"),
                    ("National", "Country Specific"),
                    ("Uncategorised", "Uncategorised"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dialogues_eu-lac", "Dialogues EU-LAC"),
                    ("dialogues_bilateral", "Dialogues Bilateral"),
                    ("dialogues_eu-country", "Dialogues EU-Country"),
                    ("dialogues_multilateral", "Dialogues multilateral"),
                    ("agreements_eu-lac", "Agreements EU-LAC"),
                    ("agreements_bilateral", "Agreements Bilateral"),
                    ("agreements_multilateral", "Agreements Multilateral"),
                    ("agreements_country_specific", "Agreements Country Specific"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="legal_bindingness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("politically-binding", "Politically-binding"),
                    ("legally-binding", "Legally-binding"),
                    ("non-binding", "Non-Binding"),
                    ("uncategorised", "Uncategorised"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="kpi_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="sector",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="target_value",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="timeframe",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sdg",
            name="label",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="theme",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Digital Transformation & Strategy",
                        "Digital Transformation & Strategy",
                    ),
                    ("Technology & Innovation", "Technology & Innovation"),
                    ("Data & Governance", "Data & Governance"),
                    (
                        "Inclusion & Social Development",
                        "Inclusion & Social Development",
                    ),
                    (
                        "Regional & International Cooperation",
                        "Regional & International Cooperation",
                    ),
                    ("Uncategorised", "Uncategorised"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="label",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
