# Generated by Django 5.2.1 on 2025-06-24 21:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_document_event_format_sourcefile_external_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="ai_check_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="ai_check_status",
            field=models.BooleanField(
                default=True, help_text="AI processing completed successfully"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="human_check_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="human_check_status",
            field=models.BooleanField(
                default=False, help_text="Human review completed"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="human_reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="User who completed human review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["ai_check_status"], name="doc_ai_check_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["human_check_status"], name="doc_human_check_idx"
            ),
        ),
    ]
