# Generated by Django 5.2.1 on 2025-06-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_actor_category_alter_actor_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="summary_file",
            field=models.FileField(
                blank=True,
                help_text="Word with summary of the document (if available).",
                null=True,
                upload_to="summaries/",
            ),
        ),
    ]
