# Generated by Django 5.2.1 on 2025-06-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_document_human_notes_alter_document_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="eu_policy_alignment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Global Gateway", "Global Gateway"),
                    ("NDICI-Global Europe", "NDICI-Global Europe"),
                    ("Digital Decade", "Digital Decade"),
                    ("Horizon Europe", "Horizon Europe"),
                    ("EU Cyber Strategy", "EU Cyber Strategy"),
                    ("Other", "Other"),
                ],
                help_text="EU policy framework alignment",
                max_length=200,
                null=True,
            ),
        ),
    ]
