# Generated by Django 5.2.1 on 2025-06-25 05:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_document_eu_policy_alignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="eu_policy_alignment",
        ),
        migrations.CreateModel(
            name="EUPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "name_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "EU Policy",
                "verbose_name_plural": "EU Policies",
                "ordering": ["name"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="eu_policy_search_vector_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name_normalized"],
                        name="eu_policy_name_norm_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="eu_policy_alignments",
            field=models.ManyToManyField(
                blank=True,
                help_text="EU policy framework alignments",
                related_name="documents",
                to="documents.eupolicy",
            ),
        ),
    ]
