# Generated by Django 5.2.6 on 2025-09-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_remove_document_eu_policy_alignment_eupolicy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Admin notes for internal use", null=True
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
