# Generated by Django 5.2.6 on 2025-10-20 18:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


def create_documentsdg_table_if_not_exists(apps, schema_editor):
    """
    Create the DocumentSDG table only if it doesn't exist.
    This handles the case where the table already exists in production.
    """
    # Use raw SQL to check if table exists and create it only if needed
    schema_editor.execute("""
        CREATE TABLE IF NOT EXISTS documents_document_sdgs (
            id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            created_at timestamp with time zone NOT NULL DEFAULT NOW(),
            updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
            relevance_score double precision DEFAULT 1.0,
            justification text,
            justification_normalized text,
            search_vector tsvector,
            document_id bigint NOT NULL,
            sdg_id bigint NOT NULL
        );
    """)
    
    # Add foreign key constraints if they don't exist
    schema_editor.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint 
                WHERE conname = 'documents_document_sdgs_document_id_fkey'
            ) THEN
                ALTER TABLE documents_document_sdgs
                ADD CONSTRAINT documents_document_sdgs_document_id_fkey
                FOREIGN KEY (document_id) 
                REFERENCES documents_document(id) 
                ON DELETE CASCADE 
                DEFERRABLE INITIALLY DEFERRED;
            END IF;
        END $$;
    """)
    
    schema_editor.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint 
                WHERE conname = 'documents_document_sdgs_sdg_id_fkey'
            ) THEN
                ALTER TABLE documents_document_sdgs
                ADD CONSTRAINT documents_document_sdgs_sdg_id_fkey
                FOREIGN KEY (sdg_id) 
                REFERENCES documents_sdg(id) 
                ON DELETE CASCADE 
                DEFERRABLE INITIALLY DEFERRED;
            END IF;
        END $$;
    """)
    
    # Add unique constraint if it doesn't exist
    schema_editor.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint 
                WHERE conname = 'documents_document_sdgs_document_id_sdg_id_key'
            ) THEN
                ALTER TABLE documents_document_sdgs
                ADD CONSTRAINT documents_document_sdgs_document_id_sdg_id_key
                UNIQUE (document_id, sdg_id);
            END IF;
        END $$;
    """)
    
    # Add indexes if they don't exist
    schema_editor.execute("""
        CREATE INDEX IF NOT EXISTS doc_sdg_search_vector_gin 
        ON documents_document_sdgs USING gin(search_vector);
    """)
    
    schema_editor.execute("""
        CREATE INDEX IF NOT EXISTS doc_sdg_just_norm_gin 
        ON documents_document_sdgs USING gin(justification_normalized gin_trgm_ops);
    """)


def reverse_create_documentsdg_table(apps, schema_editor):
    """Drop the table if we need to reverse this migration"""
    schema_editor.execute("DROP TABLE IF EXISTS documents_document_sdgs CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_admin_notes_alter_document_title'),
    ]

    operations = [
        # Use RunPython to create the table with IF NOT EXISTS logic
        migrations.RunPython(
            create_documentsdg_table_if_not_exists,
            reverse_create_documentsdg_table
        ),
        # Now we can safely alter the field since we know the table exists
        migrations.AlterField(
            model_name='document',
            name='sdgs',
            field=models.ManyToManyField(blank=True, related_name='documents', through='documents.DocumentSDG', to='documents.sdg'),
        ),
    ]
