# Generated by Django 5.2.6 on 2025-10-21 20:50

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


def create_documentsdg_if_not_exists(apps, schema_editor):
    """
    Crea la tabla DocumentSDG solo si no existe.
    Esto permite que la migración funcione tanto en entornos nuevos como en
    producción donde la tabla ya existe.
    """
    if schema_editor.connection.vendor != 'postgresql':
        # Si no es PostgreSQL, usar el comportamiento por defecto
        return
    
    with schema_editor.connection.cursor() as cursor:
        # Crear tabla solo si no existe
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS documents_document_sdgs (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
                relevance_score double precision DEFAULT 1.0,
                justification text,
                justification_normalized text,
                search_vector tsvector,
                document_id bigint NOT NULL,
                sdg_id bigint NOT NULL
            );
        """)
        
        # Agregar foreign keys solo si no existen
        cursor.execute("""
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'documents_document_sdgs_document_id_fkey'
                ) THEN
                    ALTER TABLE documents_document_sdgs
                    ADD CONSTRAINT documents_document_sdgs_document_id_fkey
                    FOREIGN KEY (document_id) 
                    REFERENCES documents_document(id) 
                    ON DELETE CASCADE 
                    DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END $$;
        """)
        
        cursor.execute("""
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'documents_document_sdgs_sdg_id_fkey'
                ) THEN
                    ALTER TABLE documents_document_sdgs
                    ADD CONSTRAINT documents_document_sdgs_sdg_id_fkey
                    FOREIGN KEY (sdg_id) 
                    REFERENCES documents_sdg(id) 
                    ON DELETE CASCADE 
                    DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END $$;
        """)
        
        # Agregar columnas si no existen (para tablas existentes sin estas columnas)
        cursor.execute("""
            DO $$ 
            BEGIN
                -- Agregar relevance_score si no existe
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'documents_document_sdgs' 
                    AND column_name = 'relevance_score'
                ) THEN
                    ALTER TABLE documents_document_sdgs 
                    ADD COLUMN relevance_score double precision DEFAULT 1.0;
                END IF;
                
                -- Agregar justification si no existe
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'documents_document_sdgs' 
                    AND column_name = 'justification'
                ) THEN
                    ALTER TABLE documents_document_sdgs 
                    ADD COLUMN justification text;
                END IF;
                
                -- Agregar justification_normalized si no existe
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'documents_document_sdgs' 
                    AND column_name = 'justification_normalized'
                ) THEN
                    ALTER TABLE documents_document_sdgs 
                    ADD COLUMN justification_normalized text;
                END IF;
                
                -- Agregar search_vector si no existe
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'documents_document_sdgs' 
                    AND column_name = 'search_vector'
                ) THEN
                    ALTER TABLE documents_document_sdgs 
                    ADD COLUMN search_vector tsvector;
                END IF;
                
                -- Agregar created_at si no existe
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'documents_document_sdgs' 
                    AND column_name = 'created_at'
                ) THEN
                    ALTER TABLE documents_document_sdgs 
                    ADD COLUMN created_at timestamp with time zone DEFAULT NOW();
                END IF;
                
                -- Agregar updated_at si no existe
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'documents_document_sdgs' 
                    AND column_name = 'updated_at'
                ) THEN
                    ALTER TABLE documents_document_sdgs 
                    ADD COLUMN updated_at timestamp with time zone DEFAULT NOW();
                END IF;
            END $$;
        """)
        
        # Agregar unique constraint solo si no existe
        cursor.execute("""
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'documents_document_sdgs_document_id_sdg_id_key'
                ) THEN
                    ALTER TABLE documents_document_sdgs
                    ADD CONSTRAINT documents_document_sdgs_document_id_sdg_id_key
                    UNIQUE (document_id, sdg_id);
                END IF;
            END $$;
        """)
        
        # Agregar índices solo si no existen (ahora que sabemos que las columnas existen)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS doc_sdg_search_vector_gin 
            ON documents_document_sdgs USING gin(search_vector);
        """)
        
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS doc_sdg_just_norm_gin 
            ON documents_document_sdgs USING gin(justification_normalized gin_trgm_ops);
        """)


def reverse_create_documentsdg(apps, schema_editor):
    """Eliminar la tabla al revertir la migración"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS documents_document_sdgs CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_admin_notes_alter_document_title'),
    ]

    operations = [
        # Usar SeparateDatabaseAndState para manejar estado y DB por separado
        migrations.SeparateDatabaseAndState(
            # Operaciones de estado (lo que Django piensa que existe)
            state_operations=[
                migrations.CreateModel(
                    name='DocumentSDG',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('relevance_score', models.FloatField(blank=True, default=1.0, null=True)),
                        ('justification', models.TextField(blank=True, null=True)),
                        ('justification_normalized', models.TextField(blank=True, editable=False, null=True)),
                        ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                        ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                        ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.sdg')),
                    ],
                    options={
                        'verbose_name': 'Document–SDG Link',
                        'verbose_name_plural': 'Document–SDG Links',
                        'db_table': 'documents_document_sdgs',
                        'unique_together': {('document', 'sdg')},
                    },
                ),
                migrations.AlterField(
                    model_name='document',
                    name='sdgs',
                    field=models.ManyToManyField(blank=True, related_name='documents', through='documents.DocumentSDG', to='documents.sdg'),
                ),
                migrations.AddIndex(
                    model_name='documentsdg',
                    index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='doc_sdg_search_vector_gin'),
                ),
                migrations.AddIndex(
                    model_name='documentsdg',
                    index=django.contrib.postgres.indexes.GinIndex(fields=['justification_normalized'], name='doc_sdg_just_norm_gin', opclasses=['gin_trgm_ops']),
                ),
            ],
            # Operaciones de base de datos (lo que realmente se ejecuta en PostgreSQL)
            database_operations=[
                migrations.RunPython(
                    create_documentsdg_if_not_exists,
                    reverse_create_documentsdg
                ),
            ],
        ),
    ]
