# Generated by Django 5.2.12 on 2026-03-03 19:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_documentsdg_alter_document_sdgs_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualitativeIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Stable machine-readable identifier, e.g. MICRO_STAKEHOLDER_DIVERSITY",
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("micro", "Micro"),
                            ("meso", "Meso"),
                            ("macro", "Macro"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("engagement", "Stakeholder Engagement"),
                            ("policy", "Policy Influence"),
                            ("trust", "Collaborative Trust"),
                            ("inclusivity", "Communication Inclusivity"),
                            ("impact", "Long-term Impact"),
                            ("alignment", "Regional Alignment"),
                            ("continuity", "Continuity of Practice"),
                            ("representation", "Institutional Representation"),
                            ("diversity", "Stakeholder Diversity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive indicators are skipped during LLM processing",
                    ),
                ),
                (
                    "label_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Qualitative Indicator",
                "verbose_name_plural": "Qualitative Indicators",
                "ordering": ["level", "label"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="qual_ind_search_vector_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["label_normalized"],
                        name="qual_ind_label_norm_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentQualitativeIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="LLM-computed relevance score 0.0–1.0",
                        null=True,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True, help_text="LLM explanation for the score", null=True
                    ),
                ),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        help_text="Key quote or passage extracted from the document",
                        null=True,
                    ),
                ),
                (
                    "justification_normalized",
                    models.TextField(blank=True, editable=False, null=True),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualitative_indicators",
                        to="documents.document",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_links",
                        to="documents.qualitativeindicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document–Qualitative Indicator Link",
                "verbose_name_plural": "Document–Qualitative Indicator Links",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="doc_qual_ind_search_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["justification_normalized"],
                        name="doc_qual_ind_just_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
                "unique_together": {("document", "indicator")},
            },
        ),
    ]
